Convolutional neural network (CNN): Use MNIST Fashion Dataset and create a classifier
to classify fashion clothing into categories.

In [1]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load training and testing data from separate CSV files
train_df = pd.read_csv("fashion-mnist_train.csv")
test_df = pd.read_csv("fashion-mnist_test.csv")

# Prepare training data
X_train = train_df.iloc[:, 1:].values / 255.0  # Normalize pixel values
y_train = train_df.iloc[:, 0].values
X_train = X_train.reshape(-1, 28, 28, 1)

# Prepare testing data
X_test = test_df.iloc[:, 1:].values / 255.0
y_test = test_df.iloc[:, 0].values
X_test = X_test.reshape(-1, 28, 28, 1)

# Build the model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_data=(X_test, y_test))

# Evaluate the model
test_acc = model.evaluate(X_test, y_test)[1]
print(f"Test Accuracy: {test_acc:.4f}")

# Label mapping
label_names = {
    0: "T-shirt/top",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle boot"
}

# Display predictions for the first 5 test samples
for i in range(5):
    pred = model.predict(X_test[i].reshape(1, 28, 28, 1)).argmax()
    actual = y_test[i]
    print(f"Predicted: {label_names[pred]} | Actual: {label_names[actual]}")

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.7741 - loss: 0.6623 - val_accuracy: 0.8820 - val_loss: 0.3519
Epoch 2/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8789 - loss: 0.3517 - val_accuracy: 0.8917 - val_loss: 0.3192
Epoch 3/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.8929 - loss: 0.3085 - val_accuracy: 0.8970 - val_loss: 0.3038
Epoch 4/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9007 - loss: 0.2831 - val_accuracy: 0.8978 - val_loss: 0.2954
Epoch 5/5
938/938 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9053 - loss: 0.2646 - val_accuracy: 0.9014 - val_loss: 0.2818
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8958 - loss: 0.2863
Test Accuracy: 0.9014
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Predicted: T-shirt/top | Actual: T-shirt/top
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Predicted: Trouser | Actual: Trouser
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Predicted: Shirt | Actual: Pullover
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Predicted: Pullover | Actual: Pullover
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Predicted: Dress | Actual: Dress

In [2]:
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,32,23,14,20,0,0,1,0,0,0
9996,6,0,0,0,0,0,0,0,0,0,...,0,0,0,2,52,23,28,0,0,0
9997,8,0,0,0,0,0,0,0,0,0,...,175,172,172,182,199,222,42,0,1,0
9998,8,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9999,1,0,0,0,0,0,0,0,140,119,...,111,95,75,44,1,0,0,0,0,0

0: T-shirt/top

1: Trouser

2: Pullover

3: Dress

4: Coat

5: Sandal

6: Shirt

7: Sneaker

8: Bag

9: Ankle boot